[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "C9PUTGahBKhniD2rFVGgWeWUyF12KCNiFh7pXJEQjLjA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/aviral10x/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
